### ISSUE TITLE
Table mode not saving changes

### ISSUE THREAD

**Issue by NeZios** [intuitem/ciso-assistant-community#2193]
**Describe the bug**
Inside an audit, when I go in table mode and I edit any measure, the change is not saved. 
To save any measure I have to go inside a measure, do the modification and hit save.

**To Reproduce**
1. With Quick Start, create a CCB Cyberfundamentals audit 
2. Edit your new audit created and check "documentation score" into the plus menu
3. Go in table mode and check the "check to enable scoring" => **FIRST issue : we have to refresh to see the scoring.** 
4. Once refresh, we can see our implementation score and documentation score bar, start to put a score, and an observation. 
5. Refresh and you will see that none of your modification has been taking into account

**Expected behavior**
The measure should be saved correctly inside Table Mode. 

**Environment (please complete the following information):**
 - Device: DELL laptop
 - OS: Windows 11
 - Browser: Edge 137.0.3296.93 
 - CISO Assistant Version: v2.6.1 Build: 6589af17f

**Comment by eric-intuitem** [comment]
Thanks for the report. We cannot reproduce the problem. Please contact us on Discord to schedule a troubleshooting session.

**Comment by NeZios** [comment]
Hello, I just edited the issue to add details. 
Here is a video showing the issue. 

https://github.com/user-attachments/assets/7ed91366-c614-457d-aa15-4e73292707d6

**Comment by ab-smith** [comment]
fixed in #2198

**Comment by NeZios** [comment]
Hello, I just updated to latest update, excited to test it out, and the issue is fixed only for the "observation" in table mode. 
**The changes made in the Implementation score and the documentation score are still not saving.** 
Thanks in advance,

**Comment by NeZios** [comment]
https://github.com/user-attachments/assets/4d081730-3725-425c-8ef1-c1413a9078d4

**Comment by NeZios** [comment]
Here is a video of the two issues : 

1. When the "check to enable scoring" is enabled, the page goes blank and you have to go up the page again to find your ciso assistant
2. Documentation score is not saving, and implementation score is sometimes not saving properly. 
Thanks

**Comment by ab-smith** [comment]
one more fix for strange space has been fixed in v2.6.3
